FROM silkeh/clang:16-unstable

RUN apt update && apt install -y python3-pip git ninja-build pipx

RUN apt install wget && wget https://github.com/Kitware/CMake/releases/download/v3.26.4/cmake-3.26.4-linux-x86_64.sh
RUN bash ./cmake-3.26.4-linux-x86_64.sh --prefix=/usr/local --exclude-subdir --skip-license

RUN pipx run conan==1.60.0 --version

RUN apt install -y libc++-16-dev libc++abi-16-dev


# replace broken symlink
# /usr/lib/clang/16/include -> ../../llvm-16/lib/clang/16.0.5/include
# /usr/lib/clang/16/lib -> ../../llvm-16/lib/clang/16.0.5/lib
RUN cd /usr/lib/clang/16 && ln -s ../../llvm-16/lib/clang/16/include include --force
RUN cd /usr/lib/clang/16 && ln -s ../../llvm-16/lib/clang/16/lib lib --force


COPY . /cmake-cpp-modules-template
WORKDIR cmake-cpp-modules-template
RUN mkdir -p build/clang


#RUN pipx run conan==1.60.0 install . -g cmake_multi -if build/clang -s build_type=Debug --build=missing --profile=profile-clang.txt
RUN pipx run conan==1.60.0 install . -g cmake_multi -if build/clang -s build_type=Release --build=missing --profile=profile-clang-silkeh.txt

RUN cmake -B build/clang -G "Ninja Multi-Config" -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DCONAN_COMPILER=clang -DCONAN_COMPILER_VERSION=16
# RUN cmake --build build/clang --config Release -j8
