FROM debian:forky

# CMake
RUN apt update
RUN apt install -y clang-22 clang-tools-22 libc++-22-dev libc++abi-22-dev
RUN apt install -y git cmake ninja-build pipx

# Conan
RUN pipx install --global conan==2.29.0
RUN conan profile detect

# Cache Conan packages
WORKDIR project
COPY conanfile.txt profile-clang-docker.txt /project
RUN conan install -of build/clang -s build_type=Release -b=missing -pr=profile-clang-docker.txt .

# Build Project
COPY . /project
# generate build/clang/CMakePresets.json
RUN conan install -of build/clang -s build_type=Release -b=missing -pr=profile-clang-docker.txt .

RUN cmake -B build/clang --preset=conan-clang-x86_64
RUN cmake --build build/clang --config Release -j8

# Test
# CMD ctest -C Release -T test --test-dir build/clang --no-compress-output --verbose
